version: '3.8'
services:
  app:
    build: ./app
    container_name: app
    restart: unless-stopped
    environment:
      - AGENT_HOSTNAME=otel-collector
    networks:
      - docknet
    depends_on:
      - prometheus
      - otel-collector
    ports:
      - 5000:5000
    
  otel-collector:
    image: otel/opentelemetry-collector:0.25.0
    container_name: otel-collector
    ports:
      - "6831:6831"
      - "14268:14268"
      - "4317:4317"
    volumes:
      - ./configs/otel-collector/otel-collector.yml:/config/otel-collector.yaml
    command:
      - --config=/config/otel-collector.yaml
    depends_on:
      - tempo
    networks:
      - docknet

  tempo:
    image: grafana/tempo:2.0.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3100:3100"
      - "55680:55680"
      #- "14268:14268"  # jaeger ingest
      #- "3200:3200"   # tempo
      #- "4317:4317"  # otlp grpc
      #- "4318:4318"  # otlp http
      #- "9411:9411"   # zipkin
    volumes:
      - ./configs/tempo/tempo.yml:/etc/tempo.yaml
      #- ./data/tempo:/tmp/tempo
    networks:
      - docknet

  prometheus:
    image: prom/prometheus:v2.37.6
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--storage.tsdb.retention.time=2d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    networks:
      - docknet

  grafana:
    image: grafana/grafana:9.4.3
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./configs/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./configs/grafana/ds_prometheus.yml:/etc/grafana/provisioning/dashboards/ds_prometheus.yml
      - ./configs/grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    env_file:
      - ./docker.env
    networks:
      - docknet

networks:
  docknet: 
    name: docknet
