receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  otlp:
    endpoint: tempo:55680
    insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]