receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  otlp:
    endpoint: tempo:4317 # https://github.com/grafana/tempo/issues/768#issuecomment-862353390
    insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]